services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./app:/backend/app
    environment:
      - DATABASE_API=127.0.0.1:8080

volumes:
  database_data: