services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./app:/backend/app
    env_file:
      - .env

volumes:
  database_data: